#!/usr/bin/env bash
# installs nginx web server on a remote server
sudo apt-get update
# installing ngix
sudo apt-get install -y nginx
# allowing ngix http
uwf allow 'Nginx HTTP'
echo"Hello World!" |sudo tee /var/www/html/index.html
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.calistus.com permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default


# starting nginx
service nginx start